#version: "3"
#services:
#  docker-mysql:
#    restart: always
#    container_name: mysql
#    image: mysql
#    volumes:
#      - rosterVolume
#    environment:
#      MYSQL_DATABASE: airlines
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: '%'
#    ports:
#      - "3306:3306"
#   networks:
#      - microservices_bridge
#  roster:
#    restart:  "no"
#    container_name: roster
#    build: ./
#    expose:
#      - 8082
#    ports:
#      - 8082:8082
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/airlines
#      eureka.client.serviceUrl.defaultZone: http://host.docker.internal:8761/eureka/
#    depends_on:
#      - docker-mysql
#    networks:
#      - microservices_bridge
#networks:
#  microservices_bridge:
#
version: "3"
services:
  roster:
    image: roster_roster
    build: ./
    container_name: roster
    ports:
      - "8082:8082"
    networks:
      - microservices_bridge
    depends_on:
      - docker-mysql
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/airlines
     eureka.client.serviceUrl.defaultZone: http://192.168.65.2:8761/eureka
  docker-mysql:
    image: mysql
    networks:
      - microservices_bridge
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=airlines

networks:
  microservices_bridge:
